# Generated by Django 3.1.2 on 2020-11-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20201118_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=122)),
                ('title', models.CharField(max_length=122)),
                ('doc', models.FileField(upload_to='')),
            ],
        ),
    ]
