# Generated by Django 3.1.4 on 2020-12-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_study_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='study_materials',
            name='doc',
            field=models.FileField(default='', upload_to='Home/testFiles'),
        ),
        migrations.AlterField(
            model_name='study_materials',
            name='subject',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='study_materials',
            name='title',
            field=models.CharField(default='', max_length=122),
        ),
    ]
