# Generated by Django 3.1.4 on 2020-12-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='to',
            field=models.CharField(default='', max_length=50),
        ),
    ]
