# Generated by Django 3.1.4 on 2020-12-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_answers_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
